export const localeOptions = [
  { code: 'en', label: 'English', tag: 'en-GB', direction: 'ltr' },
  { code: 'it', label: 'Italiano', tag: 'it-IT', direction: 'ltr' },
  { code: 'nl', label: 'Nederlands', tag: 'nl-NL', direction: 'ltr' },
  { code: 'yo', label: 'Yorùbá', tag: 'yo', direction: 'ltr' },
  { code: 'ig', label: 'Igbo', tag: 'ig', direction: 'ltr' },
  { code: 'fr', label: 'Français', tag: 'fr-FR', direction: 'ltr' },
  { code: 'de', label: 'Deutsch', tag: 'de-DE', direction: 'ltr' },
  { code: 'es', label: 'Español', tag: 'es-ES', direction: 'ltr' },
  { code: 'pt', label: 'Português', tag: 'pt-PT', direction: 'ltr' },
  { code: 'ar', label: 'العربية', tag: 'ar', direction: 'rtl' },
  { code: 'zh', label: '简体中文', tag: 'zh-Hans', direction: 'ltr' },
] as const;

export type Locale = (typeof localeOptions)[number]['code'];
export type Page = 'home' | 'services' | 'company' | 'contact' | 'privacy';

type Service = { title: string; copy: string; number: string };
type Step = { number: string; title: string; copy: string };

export type Translation = {
  nav: Record<'home' | 'services' | 'company' | 'contact' | 'language' | 'theme' | 'openMenu' | 'closeMenu' | 'primaryNavigation' | 'skipToContent' | 'light' | 'dark', string>;
  common: Record<'getInTouch' | 'exploreServices' | 'viewServices' | 'learnMore' | 'backHome' | 'privacy' | 'companyNumber' | 'registeredIn' | 'status' | 'incorporated' | 'registeredOffice' | 'activities' | 'active' | 'privateLimited' | 'source', string>;
  home: {
    eyebrow: string;
    title: string;
    body: string;
    visualLabel: string;
    signal: string;
    signalValue: string;
    servicesEyebrow: string;
    servicesTitle: string;
    servicesBody: string;
    stepsEyebrow: string;
    stepsTitle: string;
    steps: Step[];
    services: Service[];
  };
  services: { eyebrow: string; title: string; body: string; closingTitle: string; closingBody: string; cards: Service[] };
  company: { eyebrow: string; title: string; body: string; legalTitle: string; legalBody: string; activitiesIntro: string; sourceNote: string };
  contact: {
    eyebrow: string;
    title: string;
    body: string;
    formTitle: string;
    name: string;
    email: string;
    organisation: string;
    phone: string;
    topic: string;
    message: string;
    privacy: string;
    submit: string;
    sending: string;
    successTitle: string;
    successBody: string;
    contactDetails: string;
    registeredOffice: string;
    selectTopic: string;
    topics: string[];
    errors: Record<'name' | 'email' | 'message' | 'privacy' | 'configuration' | 'rate_limit' | 'unavailable' | 'generic', string>;
  };
  privacy: { eyebrow: string; title: string; intro: string; collectionTitle: string; collectionBody: string; useTitle: string; useBody: string; retentionTitle: string; retentionBody: string; contactTitle: string; contactBody: string };
  footer: { line: string; legal: string; privacy: string; companyLink: string };
  seo: Record<Page, { title: string; description: string }>;
};

const services: Service[] = [
  { number: '01', title: 'Software development', copy: 'Web, desktop and product work shaped around the way your business actually operates.' },
  { number: '02', title: 'Integration & automation', copy: 'Connect the systems that matter, remove repeat work and make information move cleanly.' },
  { number: '03', title: 'Technical consultancy', copy: 'Bring calm to complex decisions with practical discovery, architecture and delivery support.' },
];

const steps: Step[] = [
  { number: '01', title: 'Listen first', copy: 'We start with the people, constraints and outcome that matter.' },
  { number: '02', title: 'Make it clear', copy: 'We turn complexity into a shared plan your team can use.' },
  { number: '03', title: 'Build with care', copy: 'We deliver deliberate software, with room to evolve.' },
];

const english: Translation = {
  nav: { home: 'Home', services: 'Services', company: 'Company', contact: 'Contact', language: 'Language', theme: 'Colour theme', openMenu: 'Open menu', closeMenu: 'Close menu', primaryNavigation: 'Primary navigation', skipToContent: 'Skip to content', light: 'Use light theme', dark: 'Use dark theme' },
  common: { getInTouch: 'Start a conversation', exploreServices: 'Explore services', viewServices: 'View all services', learnMore: 'Learn more', backHome: 'Back to home', privacy: 'Privacy', companyNumber: 'Company number', registeredIn: 'Registered in England & Wales', status: 'Status', incorporated: 'Incorporated', registeredOffice: 'Registered office', activities: 'Registered activities', active: 'Active', privateLimited: 'Private limited company', source: 'Source' },
  home: {
    eyebrow: 'Software development · IT consultancy',
    title: 'Software that makes the complex feel simple.',
    body: 'Huygensoft helps organisations turn ideas, disconnected tools and difficult workflows into considered digital products.',
    visualLabel: 'An abstract illustration of connected software systems.',
    signal: 'A quieter way to build',
    signalValue: 'Clear systems. Useful software.',
    servicesEyebrow: 'What we do',
    servicesTitle: 'Useful by design. Thoughtful by default.',
    servicesBody: 'From a focused integration to a complete product, our work starts with clarity and ends with software people can rely on.',
    stepsEyebrow: 'How we work',
    stepsTitle: 'Less noise. More momentum.',
    steps,
    services,
  },
  services: { eyebrow: 'Services', title: 'A calm, capable partner for complex software.', body: 'We combine product thinking with practical engineering to help teams move from uncertainty to a system that works.', closingTitle: 'Have a problem worth simplifying?', closingBody: 'Tell us what is getting in the way. We will help you find a useful next step.', cards: services },
  company: { eyebrow: 'The company', title: 'Built for the work behind better software.', body: 'Huygensoft Limited is a UK private limited company registered for software publishing, software development and IT consultancy.', legalTitle: 'Company information', legalBody: 'The facts below are taken from the public Companies House register.', activitiesIntro: 'The company is registered under the following Standard Industrial Classification activities:', sourceNote: 'Companies House company overview, checked 25 August 2026.' },
  contact: {
    eyebrow: 'Contact', title: 'Start with the problem, not the platform.', body: 'Tell us a little about what you are trying to improve. A concise brief is enough to begin a useful conversation.', formTitle: 'Your enquiry', name: 'Name', email: 'Work email', organisation: 'Organisation', phone: 'Phone (optional)', topic: 'What can we help with?', message: 'Tell us about the work', privacy: 'I agree that Huygensoft may use these details to respond to my enquiry, as described in the privacy notice.', submit: 'Send enquiry', sending: 'Sending…', successTitle: 'Thank you — your enquiry is with us.', successBody: 'We have safely received your message and will use your contact details only to respond to this enquiry.', contactDetails: 'Contact details', registeredOffice: 'Registered office', selectTopic: 'Choose a topic', topics: ['New software', 'Integration & automation', 'Technical consultancy', 'Something else'],
    errors: { name: 'Please enter a name of at least two characters.', email: 'Please enter a valid email address.', message: 'Please add a little more detail (at least 20 characters).', privacy: 'Please confirm that we may use your details to respond.', configuration: 'The contact service is being connected. Please use reach@huygensoft.com for now.', rate_limit: 'Please wait a moment before sending another enquiry.', unavailable: 'The contact service is temporarily unavailable. Please try again shortly or use reach@huygensoft.com.', generic: 'We could not send your enquiry. Please try again or use reach@huygensoft.com.' },
  },
  privacy: { eyebrow: 'Privacy', title: 'A simple explanation of how enquiries are handled.', intro: 'This notice covers the information sent through the Huygensoft contact form.', collectionTitle: 'What we collect', collectionBody: 'We collect the details you choose to provide: your name, work email, organisation, phone number, topic and message.', useTitle: 'Why we use it', useBody: 'We use your details to understand and respond to your enquiry, and to keep an appropriate record of that conversation.', retentionTitle: 'How long we keep it', retentionBody: 'We keep enquiry information only for as long as reasonably needed to respond, manage the relationship and meet applicable obligations.', contactTitle: 'Your questions', contactBody: 'For privacy questions or requests about your enquiry information, contact reach@huygensoft.com.' },
  footer: { line: 'Software development and IT consultancy, made clearer.', legal: 'Huygensoft Limited · Company No. 17250183', privacy: 'Privacy', companyLink: 'Company information' },
  seo: {
    home: { title: 'Huygensoft | Software Development & IT Consultancy', description: 'Huygensoft builds considered software and provides IT consultancy, with a focus on clear, useful digital products.' },
    services: { title: 'Services | Huygensoft', description: 'Software development, integration, automation and technical consultancy from Huygensoft.' },
    company: { title: 'Company | Huygensoft', description: 'Company information for Huygensoft Limited, a UK private limited company.' },
    contact: { title: 'Contact | Huygensoft', description: 'Start a conversation with Huygensoft about software development, integration or IT consultancy.' },
    privacy: { title: 'Privacy | Huygensoft', description: 'How Huygensoft handles information submitted through its contact form.' },
  },
};

function mergeTranslation(overrides: Partial<Translation>): Translation {
  return {
    ...english,
    ...overrides,
    nav: { ...english.nav, ...overrides.nav },
    common: { ...english.common, ...overrides.common },
    home: { ...english.home, ...overrides.home },
    services: { ...english.services, ...overrides.services },
    company: { ...english.company, ...overrides.company },
    contact: { ...english.contact, ...overrides.contact, errors: { ...english.contact.errors, ...overrides.contact?.errors } },
    privacy: { ...english.privacy, ...overrides.privacy },
    footer: { ...english.footer, ...overrides.footer },
    seo: { ...english.seo, ...overrides.seo },
  };
}

export const translations: Record<Locale, Translation> = {
  en: english,
  yo: mergeTranslation({
    nav: { home: 'Ilé', services: 'Àwọn iṣẹ́', company: 'Ilé-iṣẹ́', contact: 'Kàn sí wa', language: 'Èdè', theme: 'Àkòrí àwọ̀', openMenu: 'Ṣí àtòjọ aṣayan', closeMenu: 'Pa àtòjọ aṣayan', primaryNavigation: 'Ìdarí ojú-ìwé àkọ́kọ́', skipToContent: 'Fò sí àkóónú', light: 'Lo àkòrí ìmọ́lẹ̀', dark: 'Lo àkòrí òkùnkùn' },
    common: { getInTouch: 'Bẹ̀rẹ̀ ìjíròrò', exploreServices: 'Ṣàwárí àwọn iṣẹ́', viewServices: 'Wo gbogbo iṣẹ́', learnMore: 'Kọ́ síi', backHome: 'Padà sí ojú-ìwé àkọ́kọ́', privacy: 'Ìpamọ́', companyNumber: 'Nọ́mbà ilé-iṣẹ́', registeredIn: 'A forúkọ sílẹ̀ ní ilẹ̀ Gẹ̀ẹ́sì àti Wales', status: 'Ìpo', incorporated: 'Ọjọ́ ìdásílẹ̀', registeredOffice: 'Ọ́fíìsì ìfọ̀rúkọsílẹ̀', activities: 'Àwọn iṣẹ́ tí a forúkọ sílẹ̀', active: 'Ń ṣiṣẹ́', privateLimited: 'Ilé-iṣẹ́ aládàáni tí ojúṣe rẹ̀ ní ààlà', source: 'Orísun' },
    home: {
      eyebrow: 'Ìdàgbàsókè sọ́fitiwia · Ìmọ̀ràn IT',
      title: 'Sọ́fitiwia tí ń jẹ́ kí ohun tó díjú rọrùn.',
      body: 'Huygensoft ń ràn àwọn àjọ lọ́wọ́ láti yí àwọn èrò, àwọn irinṣẹ́ tí kò so pọ̀ àti àwọn ìlànà iṣẹ́ tó nira padà sí àwọn ọjà oní-nọ́mbà tí a gbèrò dáadáa.',
      visualLabel: 'Àwòrán àfiwé àwọn ètò sọ́fitiwia tí a so pọ̀.',
      signal: 'Ọ̀nà tó túbọ̀ balẹ̀ láti kọ́ ọ',
      signalValue: 'Àwọn ètò tó mọ́. Ètò ìṣàmúlò tó wúlò.',
      servicesEyebrow: 'Ohun tá a ń ṣe',
      servicesTitle: 'A dá a láti wúlò. A ṣe é pẹ̀lú ìrònú.',
      servicesBody: 'Láti ìsopọ̀ ètò tó dojú kọ ohun kan sí ọjà pípé, iṣẹ́ wa bẹ̀rẹ̀ pẹ̀lú ìmọ̀ tó yé kedere, ó sì parí pẹ̀lú sọ́fitiwia tí ènìyàn lè gbẹ́kẹ̀ lé.',
      stepsEyebrow: 'Bí a ṣe ń ṣiṣẹ́',
      stepsTitle: 'Ìdàrúdàpọ̀ kéré. Ìlọsíwájú púpọ̀.',
      steps: [{ number: '01', title: 'A kọ́kọ́ gbọ́', copy: 'A bẹ̀rẹ̀ pẹ̀lú àwọn ènìyàn, àwọn ìdíwọ̀n àti àbájáde tó ṣe pàtàkì.' }, { number: '02', title: 'A jẹ́ kó yé kedere', copy: 'A yí ohun tó díjú padà sí ètò tí gbogbo ẹgbẹ́ yín lè lò.' }, { number: '03', title: 'A kọ́ ọ pẹ̀lú ìfarabalẹ̀', copy: 'A ṣe sọ́fitiwia tí a gbèrò dáadáa, tí ó ní ààyè láti dàgbà síi.' }],
      services: [{ number: '01', title: 'Ìdàgbàsókè sọ́fitiwia', copy: 'Iṣẹ́ wẹ́ẹ̀bù, ẹ̀rọ orí kọ̀ǹpútà àti ọjà tí a ṣe ní ìbámu pẹ̀lú bí ilé-iṣẹ́ yín ṣe ń ṣiṣẹ́ lóòótọ́.' }, { number: '02', title: 'Ìsopọ̀ àti ìmúṣiṣẹ́ aládàáṣe', copy: 'So àwọn ètò tó ṣe pàtàkì pọ̀, yọ iṣẹ́ àtúnṣe kúrò, kí ìwífún sì máa lọ láìsí ìdènà.' }, { number: '03', title: 'Ìmọ̀ràn nípa ìmọ̀-ẹ̀rọ', copy: 'Mú ìbàlẹ̀ wá sí àwọn ìpinnu tó díjú pẹ̀lú ìwádìí ìbẹ̀rẹ̀, àpẹrẹ ètò àti ìtìlẹ́yìn ìmúṣẹ́ tó wúlò.' }],
    },
    services: { eyebrow: 'Àwọn iṣẹ́', title: 'Alábàáṣiṣẹ́ tó balẹ̀, tó sì ní agbára fún sọ́fitiwia tó díjú.', body: 'A darapọ̀ ìrònú nípa ọjà pẹ̀lú ìṣẹ̀dá ẹ̀rọ tó wúlò láti ràn àwọn ẹgbẹ́ lọ́wọ́ láti kúrò nínú àìdánilójú sí ètò tó ń ṣiṣẹ́.', closingTitle: 'Ṣé ẹ ní ìṣòro tó yẹ kí a mú rọrùn?', closingBody: 'Sọ ohun tó ń dí yín lọ́wọ́ fún wa. A máa ràn yín lọ́wọ́ láti rí ìgbésẹ̀ tó kàn tó sì wúlò.', cards: [{ number: '01', title: 'Ìdàgbàsókè sọ́fitiwia', copy: 'Iṣẹ́ wẹ́ẹ̀bù, ẹ̀rọ orí kọ̀ǹpútà àti ọjà tí a ṣe ní ìbámu pẹ̀lú bí ilé-iṣẹ́ yín ṣe ń ṣiṣẹ́ lóòótọ́.' }, { number: '02', title: 'Ìsopọ̀ àti ìmúṣiṣẹ́ aládàáṣe', copy: 'So àwọn ètò tó ṣe pàtàkì pọ̀, yọ iṣẹ́ àtúnṣe kúrò, kí ìwífún sì máa lọ láìsí ìdènà.' }, { number: '03', title: 'Ìmọ̀ràn nípa ìmọ̀-ẹ̀rọ', copy: 'Mú ìbàlẹ̀ wá sí àwọn ìpinnu tó díjú pẹ̀lú ìwádìí ìbẹ̀rẹ̀, àpẹẹrẹ ètò àti ìtìlẹ́yìn ìmúṣẹ́ tó wúlò.' }] },
    company: { eyebrow: 'Ilé-iṣẹ́ náà', title: 'A kọ́ ọ fún iṣẹ́ tó wà lẹ́yìn sọ́fitiwia tó dára jù.', body: 'Huygensoft Limited jẹ́ ilé-iṣẹ́ aládàáni tí ojúṣe rẹ̀ ní ààlà ní UK, tí a forúkọ sílẹ̀ fún títẹ̀jade sọ́fitiwia, ìdàgbàsókè sọ́fitiwia àti ìmọ̀ràn IT.', legalTitle: 'Ìwífún ilé-iṣẹ́', legalBody: 'Àwọn òtítọ́ tó wà nísàlẹ̀ ni a mú láti inú ìforúkọsílẹ̀ gbangba ti Companies House.', activitiesIntro: 'A forúkọ sílẹ̀ ilé-iṣẹ́ náà lábẹ́ àwọn ẹ̀ka iṣẹ́ Standard Industrial Classification wọ̀nyí:', sourceNote: 'Àkótán ilé-iṣẹ́ ní Companies House, tí a ṣàyẹ̀wò ní ọjọ́ 25 Oṣù Kẹjọ 2026.' },
    contact: { eyebrow: 'Kàn sí wa', title: 'Bẹ̀rẹ̀ pẹ̀lú ìṣòro, kì í ṣe pẹpẹ.', body: 'Sọ díẹ̀ fún wa nípa ohun tí ẹ fẹ́ mú sunwọ̀n síi. Àkótán kúkúrú ti tó láti bẹ̀rẹ̀ ìjíròrò tó wúlò.', formTitle: 'Ìbéèrè yín', name: 'Orúkọ', email: 'Íméèlì iṣẹ́', organisation: 'Àjọ', phone: 'Fóònù (àṣàyàn)', topic: 'Kí la lè ràn yín lọ́wọ́ nínú rẹ̀?', message: 'Sọ fún wa nípa iṣẹ́ náà', privacy: 'Mo fohùn sí i pé Huygensoft lè lo àwọn àlàyé wọ̀nyí láti dáhùn ìbéèrè mi, gẹ́gẹ́ bí a ṣe ṣàlàyé nínú àkíyèsí ìpamọ́.', submit: 'Firanṣẹ́ ìbéèrè', sending: 'Ń ránṣẹ́…', successTitle: 'Ẹ ṣé — a ti gba ìbéèrè yín.', successBody: 'A ti gba ifiranṣẹ yín láìléwu, a ó sì lo àwọn àlàyé ìbánisọ̀rọ̀ yín láti dáhùn ìbéèrè yìí nìkan.', contactDetails: 'Àlàyé ìbánisọ̀rọ̀', registeredOffice: 'Ọ́fíìsì ìfọ̀rúkọsílẹ̀', selectTopic: 'Yan kókó-ọrọ̀ kan', topics: ['Sọ́fitiwia tuntun', 'Ìsopọ̀ àti ìmúṣiṣẹ́ aládàáṣe', 'Ìmọ̀ràn nípa ìmọ̀-ẹ̀rọ', 'Ohun mìíràn'], errors: { name: 'Jọ̀wọ́ tẹ orúkọ tí ó ní àmì méjì ó kéré tán.', email: 'Jọ̀wọ́ tẹ àdírẹ́sì íméèlì tó tọ́.', message: 'Jọ̀wọ́ ṣàfikún àlàyé díẹ̀ sí i (ó kéré tán àmì 20).', privacy: 'Jọ̀wọ́ jẹ́rìí sí i pé a lè lo àlàyé yín láti dáhùn.', configuration: 'A ń so iṣẹ́ ìbánisọ̀rọ̀ pọ̀. Jọ̀wọ́ lo reach@huygensoft.com fún báyìí.', rate_limit: 'Jọ̀wọ́ dúró díẹ̀ kí ẹ tó fi ìbéèrè mìíràn ránṣẹ́.', unavailable: 'Iṣẹ́ ìbánisọ̀rọ̀ kò sí fún ìgbà díẹ̀. Jọ̀wọ́ tún gbìyànjú láìpẹ́ tàbí lo reach@huygensoft.com.', generic: 'A kò lè fi ìbéèrè yín ránṣẹ́. Jọ̀wọ́ tún gbìyànjú tàbí lo reach@huygensoft.com.' } },
    privacy: { eyebrow: 'Ìpamọ́', title: 'Àlàyé tó rọrùn nípa bí a ṣe ń ṣàkóso ìbéèrè.', intro: 'Àkíyèsí yìí ṣàlàyé ìwífún tí a fi ránṣẹ́ nípasẹ̀ fọ́ọ̀mù ìbánisọ̀rọ̀ Huygensoft.', collectionTitle: 'Ohun tá a ń kó jọ', collectionBody: 'A ń kó àwọn àlàyé tí ẹ yàn láti pèsè jọ: orúkọ, íméèlì iṣẹ́, àjọ, nọ́mbà fóònù, kókó-ọrọ̀ àti ifiranṣẹ.', useTitle: 'Ìdí tá a fi ń lò ó', useBody: 'A ń lo àlàyé yín láti lóye àti láti dáhùn ìbéèrè yín, àti láti pa àkọsílẹ̀ tó yẹ ti ìjíròrò náà mọ́.', retentionTitle: 'Bí a ṣe ń pa á mọ́ pẹ́ tó', retentionBody: 'A máa ń pa ìwífún ìbéèrè mọ́ fún àkókò tí ó yẹ nìkan, láti dáhùn, láti ṣàkóso ìbáṣepọ̀ náà, àti láti mú àwọn ojúṣe tó bá kan wa ṣẹ.', contactTitle: 'Àwọn ìbéèrè yín', contactBody: 'Fún ìbéèrè nípa ìpamọ́ tàbí ìbéèrè nípa ìwífún ìbéèrè yín, kàn sí reach@huygensoft.com.' },
    footer: { line: 'Ìdàgbàsókè sọ́fitiwia àti ìmọ̀ràn IT, tí a jẹ́ kó yé kedere.', legal: 'Huygensoft Limited · Nọ́mbà Ilé-iṣẹ́ 17250183', privacy: 'Ìpamọ́', companyLink: 'Ìwífún ilé-iṣẹ́' },
    seo: { home: { title: 'Huygensoft | Ìdàgbàsókè sọ́fitiwia àti ìmọ̀ràn IT', description: 'Huygensoft ń kọ sọ́fitiwia tí a gbèrò dáadáa, ó sì ń pèsè ìmọ̀ràn IT fún àwọn ọjà oní-nọ́mbà tó mọ́ tí ó sì wúlò.' }, services: { title: 'Àwọn iṣẹ́ | Huygensoft', description: 'Ìdàgbàsókè sọ́fitiwia, ìsopọ̀, ìmúṣiṣẹ́ aládàáṣe àti ìmọ̀ràn nípa ìmọ̀-ẹ̀rọ láti ọ̀dọ̀ Huygensoft.' }, company: { title: 'Ilé-iṣẹ́ | Huygensoft', description: 'Ìwífún nípa Huygensoft Limited, ilé-iṣẹ́ aládàáni tí ojúṣe rẹ̀ ní ààlà ní UK.' }, contact: { title: 'Kàn sí wa | Huygensoft', description: 'Bẹ̀rẹ̀ ìjíròrò pẹ̀lú Huygensoft nípa ìdàgbàsókè sọ́fitiwia, ìsopọ̀ tàbí ìmọ̀ràn IT.' }, privacy: { title: 'Ìpamọ́ | Huygensoft', description: 'Bí Huygensoft ṣe ń ṣàkóso ìwífún tí a fi ránṣẹ́ nípasẹ̀ fọ́ọ̀mù ìbánisọ̀rọ̀ rẹ̀.' } },
  }),
  ig: mergeTranslation({
    nav: { home: 'Peeji mbụ', services: 'Ọrụ', company: 'Ụlọọrụ', contact: 'Kpọtụrụ anyị', language: 'Asụsụ', theme: 'Ụdị agba', openMenu: 'Mepee menu', closeMenu: 'Mechie menu', primaryNavigation: 'Nduzi izizi', skipToContent: 'Gaa n’ọdịnaya', light: 'Jiri ụdị ìhè', dark: 'Jiri ụdị ọchịchịrị' },
    common: { getInTouch: 'Malite mkparịta ụka', exploreServices: 'Chọpụta ọrụ anyị', viewServices: 'Lee ọrụ niile', learnMore: 'Mụtakwuo', backHome: 'Laghachi na peeji mbụ', privacy: 'Nzuzo', companyNumber: 'Nọmba ụlọọrụ', registeredIn: 'Edebanyere aha na England na Wales', status: 'Ọnọdụ', incorporated: 'Ụbọchị e hiwere', registeredOffice: 'Ụlọọrụ e debanyere aha', activities: 'Ọrụ e debanyere aha', active: 'Na-arụ ọrụ', privateLimited: 'Ụlọọrụ nkeonwe nwere oke ibu', source: 'Isi mmalite' },
    home: {
      eyebrow: 'Mmepe ngwanrọ · Ndụmọdụ IT',
      title: 'Ngwanrọ na-eme ka ihe mgbagwoju anya dị mfe.',
      body: 'Huygensoft na-enyere òtù dị iche iche aka ịgbanwe echiche, ngwá ọrụ ndị na-adịghị ejikọta onwe ha na usoro ọrụ siri ike ka ha ghọọ ngwaahịa dijitalụ e jiri nlezianya chepụta.',
      visualLabel: 'Ihe osise na-adịghị akọwapụta nke sistemụ ngwanrọ ejikọrọ ọnụ.',
      signal: 'Ụzọ dị jụụ karị isi wuo',
      signalValue: 'Sistemụ doro anya. Ngwanrọ bara uru.',
      servicesEyebrow: 'Ihe anyị na-eme',
      servicesTitle: 'A chepụtara ya ka ọ baa uru. A na-eji nlezianya eme ya.',
      servicesBody: 'Site na njikọta e lebara anya n’otu ọrụ ruo n’ngwaahịa zuru ezu, ọrụ anyị na-amalite site n’ịkọwapụta ihe nke ọma ma na-ejedebe n’ngwanrọ ndị mmadụ nwere ike ịdabere na ya.',
      stepsEyebrow: 'Otu anyị si arụ ọrụ',
      stepsTitle: 'Obere ihe ndọpụ uche. Ọganihu ka ukwuu.',
      steps: [{ number: '01', title: 'Bu ụzọ gee ntị', copy: 'Anyị na-amalite site n’ịghọta ndị mmadụ, ihe mgbochi na nsonaazụ kacha mkpa.' }, { number: '02', title: 'Mee ka o doo anya', copy: 'Anyị na-atụgharị mgbagwoju anya ka ọ bụrụ atụmatụ onye ọ bụla n’òtù gị nwere ike iji.' }, { number: '03', title: 'Jiri nlezianya wuo', copy: 'Anyị na-ebunye ngwanrọ e chepụtara n’ebumnobi, nke nwere ohere itolite.' }],
      services: [{ number: '01', title: 'Mmepe ngwanrọ', copy: 'Ọrụ weebụ, desktọpụ na ngwaahịa e mere ka ọ dabara n’ụzọ azụmahịa gị si arụ ọrụ n’eziokwu.' }, { number: '02', title: 'Njikọta na akpaaka', copy: 'Jikọta sistemụ ndị dị mkpa, wepụ ọrụ a na-eme ugboro ugboro ma mee ka ozi na-aga nke ọma.' }, { number: '03', title: 'Ndụmọdụ teknụzụ', copy: 'Weta ịdị jụụ n’ime mkpebi ndị mgbagwoju anya site n’ịchọpụta mkpa nke ọma, nhazi sistemụ na nkwado nnyefe bara uru.' }],
    },
    services: { eyebrow: 'Ọrụ', title: 'Onye mmekọ dị jụụ ma nwee nkà maka ngwanrọ dị mgbagwoju anya.', body: 'Anyị na-ejikọta echiche ngwaahịa na injiniarị bara uru iji nyere òtù aka isi n’ejighị n’aka gafee gaa n’usoro na-arụ ọrụ.', closingTitle: 'Ị nwere nsogbu kwesịrị ka e mee ka ọ dị mfe?', closingBody: 'Gwa anyị ihe na-egbochi gị. Anyị ga-enyere gị aka ịchọta nzọụkwụ ọzọ bara uru.', cards: [{ number: '01', title: 'Mmepe ngwanrọ', copy: 'Ọrụ weebụ, desktọpụ na ngwaahịa e mere ka ọ dabara n’ụzọ azụmahịa gị si arụ ọrụ n’eziokwu.' }, { number: '02', title: 'Njikọta na akpaaka', copy: 'Jikọta sistemụ ndị dị mkpa, wepụ ọrụ a na-eme ugboro ugboro ma mee ka ozi na-aga nke ọma.' }, { number: '03', title: 'Ndụmọdụ teknụzụ', copy: 'Weta ịdị jụụ n’ime mkpebi ndị mgbagwoju anya site n’ịchọpụta mkpa nke ọma, nhazi sistemụ na nkwado nnyefe bara uru.' }] },
    company: { eyebrow: 'Ụlọọrụ', title: 'E wuru ya maka ọrụ dị n’azụ ngwanrọ ka mma.', body: 'Huygensoft Limited bụ ụlọọrụ nkeonwe nwere oke ibu na UK, nke e debanyere aha maka mbipụta ngwanrọ, mmepe ngwanrọ na ndụmọdụ IT.', legalTitle: 'Ozi ụlọọrụ', legalBody: 'E si n’akwụkwọ ndekọ ọha nke Companies House nweta eziokwu ndị dị n’okpuru.', activitiesIntro: 'Edebanyere aha ụlọọrụ ahụ n’okpuru ọrụ Standard Industrial Classification ndị a:', sourceNote: 'Nchịkọta ụlọọrụ Companies House, enyochara ya na 25 Ọgọst 2026.' },
    contact: { eyebrow: 'Kpọtụrụ anyị', title: 'Bido n’nsogbu, ọ bụghị n’ikpo okwu.', body: 'Gwa anyị ntakịrị banyere ihe ị chọrọ imezi. Nkọwa dị mkpirikpi ezuola iji malite mkparịta ụka bara uru.', formTitle: 'Ajụjụ gị', name: 'Aha', email: 'Adreesị ozi-e ọrụ', organisation: 'Òtù', phone: 'Ekwentị (nhọrọ)', topic: 'Kedu ihe anyị nwere ike inyere gị aka na ya?', message: 'Gwa anyị gbasara ọrụ ahụ', privacy: 'Ekwenyere m na Huygensoft nwere ike iji nkọwa ndị a zaa ajụjụ m, dịka e kọwara n’nkwupụta nzuzo.', submit: 'Ziga ajụjụ', sending: 'Na-eziga…', successTitle: 'Daalụ — anyị enwetala ajụjụ gị.', successBody: 'Anyị ejirila nlezianya nata ozi gị, anyị ga-ejikwa nkọwa kọntaktị gị naanị zaa ajụjụ a.', contactDetails: 'Nkọwa kọntaktị', registeredOffice: 'Ụlọọrụ e debanyere aha', selectTopic: 'Họrọ isiokwu', topics: ['Ngwanrọ ọhụrụ', 'Njikọta na akpaaka', 'Ndụmọdụ teknụzụ', 'Ihe ọzọ'], errors: { name: 'Biko tinye aha nwere opekata mpe mkpụrụedemede abụọ.', email: 'Biko tinye adreesị ozi-e ziri ezi.', message: 'Biko tinye nkọwa ndị ọzọ (opekata mpe mkpụrụedemede 20).', privacy: 'Biko kwado na anyị nwere ike iji nkọwa gị zaa gị.', configuration: 'A na-ejikọ ọrụ kọntaktị ugbu a. Biko jiri reach@huygensoft.com maka ugbu a.', rate_limit: 'Biko chere ntakịrị tupu iziga ajụjụ ọzọ.', unavailable: 'Ọrụ kọntaktị adịghị ugbu a. Biko nwaa ọzọ n’oge na-adịghị anya ma ọ bụ jiri reach@huygensoft.com.', generic: 'Anyị enweghị ike iziga ajụjụ gị. Biko nwaa ọzọ ma ọ bụ jiri reach@huygensoft.com.' } },
    privacy: { eyebrow: 'Nzuzo', title: 'Nkọwa dị mfe banyere otu anyị si ejikwa ajụjụ.', intro: 'Nkwupụta a metụtara ozi e zigara site na fọm kọntaktị Huygensoft.', collectionTitle: 'Ihe anyị na-anakọta', collectionBody: 'Anyị na-anakọta nkọwa ndị ị họọrọ inye: aha gị, adreesị ozi-e ọrụ, òtù, nọmba ekwentị, isiokwu na ozi.', useTitle: 'Ihe mere anyị ji eji ya', useBody: 'Anyị na-eji nkọwa gị ghọta ma zaa ajụjụ gị, nakwa idobe ndekọ kwesịrị ekwesị nke mkparịta ụka ahụ.', retentionTitle: 'Ogologo oge anyị ji edobe ya', retentionBody: 'Anyị na-edobe ozi ajụjụ naanị ruo oge kwesịrị ekwesị iji zaa, jikwaa mmekọrịta, ma mezuo ibu ọrụ ndị metụtara ya.', contactTitle: 'Ajụjụ gị', contactBody: 'Maka ajụjụ nzuzo ma ọ bụ arịrịọ gbasara ozi ajụjụ gị, kpọtụrụ reach@huygensoft.com.' },
    footer: { line: 'Mmepe ngwanrọ na ndụmọdụ IT, eme ka ọ dokwuo anya.', legal: 'Huygensoft Limited · Nọmba Ụlọọrụ 17250183', privacy: 'Nzuzo', companyLink: 'Ozi ụlọọrụ' },
    seo: { home: { title: 'Huygensoft | Mmepe ngwanrọ na ndụmọdụ IT', description: 'Huygensoft na-emepụta ngwanrọ e jiri nlezianya chepụta ma na-enye ndụmọdụ IT, na-elekwasị anya na ngwaahịa dijitalụ doro anya ma bara uru.' }, services: { title: 'Ọrụ | Huygensoft', description: 'Mmepe ngwanrọ, njikọta, akpaaka na ndụmọdụ teknụzụ sitere na Huygensoft.' }, company: { title: 'Ụlọọrụ | Huygensoft', description: 'Ozi gbasara Huygensoft Limited, ụlọọrụ nkeonwe nwere oke ibu na UK.' }, contact: { title: 'Kpọtụrụ anyị | Huygensoft', description: 'Malite mkparịta ụka na Huygensoft gbasara mmepe ngwanrọ, njikọta ma ọ bụ ndụmọdụ IT.' }, privacy: { title: 'Nzuzo | Huygensoft', description: 'Otu Huygensoft si ejikwa ozi e nyefere site na fọm kọntaktị ya.' } },
  }),
  it: mergeTranslation({
    nav: { home: 'Pagina iniziale', services: 'Servizi', company: 'Azienda', contact: 'Contatti', language: 'Lingua', theme: 'Tema colore', openMenu: 'Apri menu', closeMenu: 'Chiudi menu', primaryNavigation: 'Navigazione principale', skipToContent: 'Vai al contenuto', light: 'Usa il tema chiaro', dark: 'Usa il tema scuro' },
    common: { getInTouch: 'Avvia una conversazione', exploreServices: 'Scopri i servizi', viewServices: 'Vedi tutti i servizi', learnMore: 'Scopri di più', backHome: 'Torna alla pagina iniziale', privacy: 'Privacy', companyNumber: 'Numero di iscrizione', registeredIn: 'Registrata in Inghilterra e Galles', status: 'Stato', incorporated: 'Costituita', registeredOffice: 'Sede legale', activities: 'Attività registrate', active: 'Attiva', privateLimited: 'Società privata a responsabilità limitata', source: 'Fonte' },
    home: {
      eyebrow: 'Sviluppo software · Consulenza IT',
      title: 'Software che rende semplice ciò che è complesso.',
      body: 'Huygensoft aiuta le organizzazioni a trasformare idee, strumenti scollegati e flussi di lavoro complessi in prodotti digitali progettati con cura.',
      visualLabel: 'Illustrazione astratta di sistemi software connessi.',
      signal: 'Un modo più sereno di costruire',
      signalValue: 'Sistemi chiari. Software utile.',
      servicesEyebrow: 'Cosa facciamo',
      servicesTitle: 'Progettato per essere utile. Pensato con cura.',
      servicesBody: "Da un'integrazione mirata a un prodotto completo, il nostro lavoro inizia dalla chiarezza e si conclude con software su cui le persone possono fare affidamento.",
      stepsEyebrow: 'Come lavoriamo',
      stepsTitle: 'Meno rumore. Più slancio.',
      steps: [{ number: '01', title: 'Prima ascoltiamo', copy: 'Partiamo dalle persone, dai vincoli e dal risultato che conta.' }, { number: '02', title: 'Facciamo chiarezza', copy: 'Trasformiamo la complessità in un piano condiviso che il tuo team può utilizzare.' }, { number: '03', title: 'Costruiamo con cura', copy: 'Realizziamo software pensato con cura, con spazio per evolversi.' }],
      services: [{ number: '01', title: 'Sviluppo software', copy: 'Soluzioni web, desktop e di prodotto modellate sul modo in cui la tua azienda opera davvero.' }, { number: '02', title: 'Integrazione e automazione', copy: 'Colleghiamo i sistemi che contano, eliminiamo il lavoro ripetitivo e facciamo circolare le informazioni senza attriti.' }, { number: '03', title: 'Consulenza tecnica', copy: 'Portiamo chiarezza alle decisioni complesse con analisi, architettura e supporto alla realizzazione concreti.' }],
    },
    services: { eyebrow: 'Servizi', title: 'Un partner competente e affidabile per software complesso.', body: "Combiniamo il pensiero di prodotto con l'ingegneria pragmatica per aiutare i team a passare dall'incertezza a un sistema che funziona.", closingTitle: 'Hai un problema che vale la pena semplificare?', closingBody: 'Raccontaci cosa ti ostacola. Ti aiuteremo a trovare un prossimo passo utile.', cards: [{ number: '01', title: 'Sviluppo software', copy: 'Soluzioni web, desktop e di prodotto modellate sul modo in cui la tua azienda opera davvero.' }, { number: '02', title: 'Integrazione e automazione', copy: 'Colleghiamo i sistemi che contano, eliminiamo il lavoro ripetitivo e facciamo circolare le informazioni senza attriti.' }, { number: '03', title: 'Consulenza tecnica', copy: 'Portiamo chiarezza alle decisioni complesse con analisi, architettura e supporto alla realizzazione concreti.' }] },
    company: { eyebrow: "L'azienda", title: 'Pensata per il lavoro che sta dietro a software migliori.', body: "Huygensoft Limited è una società privata a responsabilità limitata del Regno Unito, registrata per l'editoria di software, lo sviluppo software e la consulenza IT.", legalTitle: 'Informazioni societarie', legalBody: 'Le informazioni riportate di seguito provengono dal registro pubblico di Companies House.', activitiesIntro: 'La società è registrata per le seguenti attività della Standard Industrial Classification:', sourceNote: 'Panoramica aziendale di Companies House, verificata il 25 agosto 2026.' },
    contact: { eyebrow: 'Contatti', title: 'Parti dal problema, non dalla piattaforma.', body: 'Raccontaci brevemente cosa desideri migliorare. Un breve riepilogo basta per avviare una conversazione utile.', formTitle: 'La tua richiesta', name: 'Nome', email: 'Email di lavoro', organisation: 'Organizzazione', phone: 'Telefono (facoltativo)', topic: 'Come possiamo aiutarti?', message: 'Parlaci del progetto', privacy: "Acconsento affinché Huygensoft utilizzi questi dati per rispondere alla mia richiesta, come descritto nell'informativa sulla privacy.", submit: 'Invia richiesta', sending: 'Invio in corso…', successTitle: 'Grazie — abbiamo ricevuto la tua richiesta.', successBody: 'Abbiamo ricevuto il tuo messaggio in modo sicuro e useremo i tuoi dati di contatto esclusivamente per rispondere a questa richiesta.', contactDetails: 'Recapiti', registeredOffice: 'Sede legale', selectTopic: 'Scegli un argomento', topics: ['Nuovo software', 'Integrazione e automazione', 'Consulenza tecnica', 'Altro'], errors: { name: 'Inserisci un nome di almeno due caratteri.', email: 'Inserisci un indirizzo email valido.', message: 'Aggiungi qualche dettaglio in più, almeno 20 caratteri.', privacy: 'Conferma che possiamo usare i tuoi dati per rispondere.', configuration: 'Il servizio di contatto è in fase di configurazione. Per ora, scrivi a reach@huygensoft.com.', rate_limit: "Attendi un momento prima di inviare un'altra richiesta.", unavailable: 'Il servizio di contatto non è temporaneamente disponibile. Riprova tra poco o scrivi a reach@huygensoft.com.', generic: 'Non è stato possibile inviare la tua richiesta. Riprova o scrivi a reach@huygensoft.com.' } },
    privacy: { eyebrow: 'Privacy', title: 'Una spiegazione semplice di come gestiamo le richieste.', intro: 'Questa informativa riguarda le informazioni inviate tramite il modulo di contatto di Huygensoft.', collectionTitle: 'Cosa raccogliamo', collectionBody: 'Raccogliamo i dati che scegli di fornirci: nome, email di lavoro, organizzazione, numero di telefono, argomento e messaggio.', useTitle: 'Perché li utilizziamo', useBody: 'Utilizziamo i tuoi dati per comprendere e rispondere alla tua richiesta e per mantenere una registrazione appropriata della conversazione.', retentionTitle: 'Per quanto tempo li conserviamo', retentionBody: 'Conserviamo le informazioni relative alle richieste solo per il tempo ragionevolmente necessario a rispondere, gestire la relazione e adempiere agli obblighi applicabili.', contactTitle: 'Le tue domande', contactBody: 'Per domande sulla privacy o richieste riguardanti i dati della tua richiesta, contatta reach@huygensoft.com.' },
    footer: { line: 'Sviluppo software e consulenza IT, in modo più chiaro.', legal: 'Huygensoft Limited · N. di iscrizione 17250183', privacy: 'Privacy', companyLink: 'Informazioni societarie' },
    seo: { home: { title: 'Huygensoft | Sviluppo software e consulenza IT', description: 'Huygensoft realizza software progettato con cura e offre consulenza IT, con attenzione a prodotti digitali chiari e utili.' }, services: { title: 'Servizi | Huygensoft', description: 'Sviluppo software, integrazione, automazione e consulenza tecnica da Huygensoft.' }, company: { title: 'Azienda | Huygensoft', description: 'Informazioni societarie su Huygensoft Limited, società privata a responsabilità limitata del Regno Unito.' }, contact: { title: 'Contatti | Huygensoft', description: 'Avvia una conversazione con Huygensoft su sviluppo software, integrazione o consulenza IT.' }, privacy: { title: 'Privacy | Huygensoft', description: 'Come Huygensoft gestisce le informazioni inviate tramite il modulo di contatto.' } },
  }),
  nl: mergeTranslation({
    nav: { home: 'Startpagina', services: 'Diensten', company: 'Bedrijf', contact: 'Contact', language: 'Taal', theme: 'Kleurthema', openMenu: 'Menu openen', closeMenu: 'Menu sluiten', primaryNavigation: 'Hoofdnavigatie', skipToContent: 'Ga naar inhoud', light: 'Licht thema gebruiken', dark: 'Donker thema gebruiken' },
    common: { getInTouch: 'Start een gesprek', exploreServices: 'Ontdek onze diensten', viewServices: 'Bekijk alle diensten', learnMore: 'Meer informatie', backHome: 'Terug naar de startpagina', privacy: 'Privacy', companyNumber: 'Bedrijfsnummer', registeredIn: 'Geregistreerd in Engeland en Wales', status: 'Status', incorporated: 'Opgericht', registeredOffice: 'Statutaire zetel', activities: 'Geregistreerde activiteiten', active: 'Actief', privateLimited: 'Besloten vennootschap', source: 'Bron' },
    home: {
      eyebrow: 'Softwareontwikkeling · IT-advies',
      title: 'Software die complexiteit eenvoudig maakt.',
      body: 'Huygensoft helpt organisaties om ideeën, losstaande tools en lastige werkprocessen om te zetten in doordachte digitale producten.',
      visualLabel: 'Abstracte illustratie van verbonden softwaresystemen.',
      signal: 'Een rustigere manier om te bouwen',
      signalValue: 'Duidelijke systemen. Nuttige software.',
      servicesEyebrow: 'Wat we doen',
      servicesTitle: 'Nuttig ontworpen. Zorgvuldig doordacht.',
      servicesBody: 'Van een gerichte integratie tot een volledig product: ons werk begint met duidelijkheid en eindigt met software waarop mensen kunnen vertrouwen.',
      stepsEyebrow: 'Zo werken we',
      stepsTitle: 'Minder ruis. Meer vaart.',
      steps: [{ number: '01', title: 'Eerst luisteren', copy: 'We beginnen bij de mensen, beperkingen en het resultaat dat ertoe doet.' }, { number: '02', title: 'We maken het helder', copy: 'We vertalen complexiteit naar een gedeeld plan waarmee uw team kan werken.' }, { number: '03', title: 'We bouwen met zorg', copy: 'We leveren zorgvuldig ontworpen software die kan meegroeien.' }],
      services: [{ number: '01', title: 'Softwareontwikkeling', copy: 'Web-, desktop- en productontwikkeling, afgestemd op de manier waarop uw organisatie daadwerkelijk werkt.' }, { number: '02', title: 'Integratie en automatisering', copy: 'Koppel de systemen die ertoe doen, verminder herhaalwerk en laat informatie soepel stromen.' }, { number: '03', title: 'Technisch advies', copy: 'Breng rust in complexe beslissingen met praktische verkenning, architectuur en ondersteuning bij de oplevering.' }],
    },
    services: { eyebrow: 'Diensten', title: 'Een rustige, kundige partner voor complexe software.', body: 'We combineren productdenken met praktische techniek om teams van onzekerheid naar een systeem te brengen dat werkt.', closingTitle: 'Heeft u een probleem dat eenvoudiger kan?', closingBody: 'Vertel ons wat u belemmert. We helpen u een bruikbare volgende stap te vinden.', cards: [{ number: '01', title: 'Softwareontwikkeling', copy: 'Web-, desktop- en productontwikkeling, afgestemd op de manier waarop uw organisatie daadwerkelijk werkt.' }, { number: '02', title: 'Integratie en automatisering', copy: 'Koppel de systemen die ertoe doen, verminder herhaalwerk en laat informatie soepel stromen.' }, { number: '03', title: 'Technisch advies', copy: 'Breng rust in complexe beslissingen met praktische verkenning, architectuur en ondersteuning bij de oplevering.' }] },
    company: { eyebrow: 'Het bedrijf', title: 'Gebouwd voor het werk achter betere software.', body: 'Huygensoft Limited is een Britse besloten vennootschap, geregistreerd voor het uitgeven en ontwikkelen van software en voor IT-advies.', legalTitle: 'Bedrijfsinformatie', legalBody: 'De onderstaande gegevens zijn afkomstig uit het openbare register van Companies House.', activitiesIntro: 'De onderneming staat ingeschreven voor de volgende activiteiten volgens de Standard Industrial Classification:', sourceNote: 'Bedrijfsoverzicht van Companies House, gecontroleerd op 25 augustus 2026.' },
    contact: { eyebrow: 'Contact', title: 'Begin bij het probleem, niet bij het platform.', body: 'Vertel ons kort wat u wilt verbeteren. Een beknopte toelichting is voldoende om een zinvol gesprek te starten.', formTitle: 'Uw aanvraag', name: 'Naam', email: 'Zakelijk e-mailadres', organisation: 'Organisatie', phone: 'Telefoon (optioneel)', topic: 'Waarmee kunnen we u helpen?', message: 'Vertel ons over het werk', privacy: 'Ik ga ermee akkoord dat Huygensoft deze gegevens gebruikt om op mijn aanvraag te reageren, zoals beschreven in de privacyverklaring.', submit: 'Aanvraag versturen', sending: 'Versturen…', successTitle: 'Bedankt — we hebben uw aanvraag ontvangen.', successBody: 'We hebben uw bericht veilig ontvangen en gebruiken uw contactgegevens uitsluitend om op deze aanvraag te reageren.', contactDetails: 'Contactgegevens', registeredOffice: 'Statutaire zetel', selectTopic: 'Kies een onderwerp', topics: ['Nieuwe software', 'Integratie en automatisering', 'Technisch advies', 'Iets anders'], errors: { name: 'Vul een naam van minimaal twee tekens in.', email: 'Vul een geldig e-mailadres in.', message: 'Voeg iets meer informatie toe, minimaal 20 tekens.', privacy: 'Bevestig dat we uw gegevens mogen gebruiken om te reageren.', configuration: 'De contactservice wordt momenteel aangesloten. Gebruik voorlopig reach@huygensoft.com.', rate_limit: 'Wacht even voordat u nog een aanvraag verstuurt.', unavailable: 'De contactservice is tijdelijk niet beschikbaar. Probeer het binnenkort opnieuw of gebruik reach@huygensoft.com.', generic: 'Uw aanvraag kon niet worden verzonden. Probeer het opnieuw of gebruik reach@huygensoft.com.' } },
    privacy: { eyebrow: 'Privacy', title: 'Een eenvoudige uitleg over hoe we aanvragen behandelen.', intro: 'Deze verklaring geldt voor de informatie die via het contactformulier van Huygensoft wordt verzonden.', collectionTitle: 'Wat we verzamelen', collectionBody: 'We verzamelen de gegevens die u zelf verstrekt: naam, zakelijk e-mailadres, organisatie, telefoonnummer, onderwerp en bericht.', useTitle: 'Waarom we deze gegevens gebruiken', useBody: 'We gebruiken uw gegevens om uw aanvraag te begrijpen en te beantwoorden, en om een passend dossier van dat gesprek bij te houden.', retentionTitle: 'Hoe lang we de gegevens bewaren', retentionBody: 'We bewaren informatie over aanvragen alleen zolang dat redelijkerwijs nodig is om te reageren, de relatie te beheren en aan toepasselijke verplichtingen te voldoen.', contactTitle: 'Uw vragen', contactBody: 'Voor privacyvragen of verzoeken over de gegevens in uw aanvraag kunt u contact opnemen via reach@huygensoft.com.' },
    footer: { line: 'Softwareontwikkeling en IT-advies, helder gemaakt.', legal: 'Huygensoft Limited · Bedrijfsnummer 17250183', privacy: 'Privacy', companyLink: 'Bedrijfsinformatie' },
    seo: { home: { title: 'Huygensoft | Softwareontwikkeling en IT-advies', description: 'Huygensoft bouwt doordachte software en biedt IT-advies, met aandacht voor duidelijke en bruikbare digitale producten.' }, services: { title: 'Diensten | Huygensoft', description: 'Softwareontwikkeling, integratie, automatisering en technisch advies van Huygensoft.' }, company: { title: 'Bedrijf | Huygensoft', description: 'Bedrijfsinformatie over Huygensoft Limited, een Britse besloten vennootschap.' }, contact: { title: 'Contact | Huygensoft', description: 'Start een gesprek met Huygensoft over softwareontwikkeling, integratie of IT-advies.' }, privacy: { title: 'Privacy | Huygensoft', description: 'Hoe Huygensoft informatie behandelt die via het contactformulier wordt verstuurd.' } },
  }),
  fr: mergeTranslation({
    nav: { home: 'Accueil', services: 'Services', company: 'Entreprise', contact: 'Contact', language: 'Langue', theme: 'Thème de couleur', openMenu: 'Ouvrir le menu', closeMenu: 'Fermer le menu', primaryNavigation: 'Navigation principale', skipToContent: 'Aller au contenu', light: 'Utiliser le thème clair', dark: 'Utiliser le thème sombre' },
    common: { getInTouch: 'Démarrer une conversation', exploreServices: 'Découvrir les services', viewServices: 'Voir tous les services', learnMore: 'En savoir plus', backHome: 'Retour à l’accueil', privacy: 'Confidentialité', companyNumber: 'Numéro d’entreprise', registeredIn: 'Enregistrée en Angleterre et au pays de Galles', status: 'Statut', incorporated: 'Constituée', registeredOffice: 'Siège social', activities: 'Activités déclarées', active: 'Active', privateLimited: 'Société privée à responsabilité limitée', source: 'Source' },
    home: { eyebrow: 'Développement logiciel · Conseil IT', title: 'Des logiciels qui rendent la complexité simple.', body: 'Huygensoft aide les organisations à transformer les idées, les outils déconnectés et les processus difficiles en produits numériques réfléchis.', visualLabel: 'Illustration abstraite de systèmes logiciels connectés.', signal: 'Une façon plus calme de construire', signalValue: 'Des systèmes clairs. Des logiciels utiles.', servicesEyebrow: 'Notre travail', servicesTitle: 'Utile par conception. Réfléchi par défaut.', servicesBody: 'D’une intégration ciblée à un produit complet, nous partons de la clarté pour livrer des logiciels fiables.', stepsEyebrow: 'Notre méthode', stepsTitle: 'Moins de bruit. Plus d’élan.', steps: [{ number: '01', title: 'Écouter d’abord', copy: 'Nous commençons par les personnes, les contraintes et le résultat important.' }, { number: '02', title: 'Rendre clair', copy: 'Nous transformons la complexité en plan partagé.' }, { number: '03', title: 'Construire avec soin', copy: 'Nous livrons un logiciel volontaire, prêt à évoluer.' }], services: [{ number: '01', title: 'Développement logiciel', copy: 'Produits web, bureau et métier pensés pour vos opérations réelles.' }, { number: '02', title: 'Intégration et automatisation', copy: 'Reliez les systèmes importants et éliminez les tâches répétitives.' }, { number: '03', title: 'Conseil technique', copy: 'Des décisions plus calmes grâce à une découverte et une architecture pragmatiques.' }] },
    services: { eyebrow: 'Services', title: 'Un partenaire serein et compétent pour les logiciels complexes.', body: 'Nous associons vision produit et ingénierie pragmatique pour passer de l’incertitude à un système fonctionnel.', closingTitle: 'Un problème à simplifier ?', closingBody: 'Dites-nous ce qui vous ralentit. Nous trouverons une première étape utile.', cards: [{ number: '01', title: 'Développement logiciel', copy: 'Produits web, bureau et métier pensés pour vos opérations réelles.' }, { number: '02', title: 'Intégration et automatisation', copy: 'Reliez les systèmes importants et éliminez les tâches répétitives.' }, { number: '03', title: 'Conseil technique', copy: 'Des décisions plus calmes grâce à une découverte et une architecture pragmatiques.' }] },
    company: { eyebrow: 'L’entreprise', title: 'Conçue pour le travail qui améliore les logiciels.', body: 'Huygensoft Limited est une société britannique enregistrée pour l’édition de logiciels, le développement logiciel et le conseil IT.', legalTitle: 'Informations sur l’entreprise', legalBody: 'Les informations ci-dessous proviennent du registre public de Companies House.', activitiesIntro: 'La société est déclarée sous les activités de classification industrielle suivantes :', sourceNote: 'Aperçu Companies House, vérifié le 25 août 2026.' },
    contact: { eyebrow: 'Contact', title: 'Commencez par le problème, pas par la plateforme.', body: 'Décrivez ce que vous souhaitez améliorer. Un bref aperçu suffit pour commencer une conversation utile.', formTitle: 'Votre demande', name: 'Nom', email: 'E-mail professionnel', organisation: 'Organisation', phone: 'Téléphone (facultatif)', topic: 'Comment pouvons-nous vous aider ?', message: 'Parlez-nous du travail', privacy: 'J’accepte que Huygensoft utilise ces informations pour répondre à ma demande, comme indiqué dans l’avis de confidentialité.', submit: 'Envoyer la demande', sending: 'Envoi…', successTitle: 'Merci — votre demande est bien reçue.', successBody: 'Nous avons reçu votre message et utiliserons vos coordonnées uniquement pour y répondre.', contactDetails: 'Coordonnées', registeredOffice: 'Siège social', selectTopic: 'Choisissez un sujet', topics: ['Nouveau logiciel', 'Intégration et automatisation', 'Conseil technique', 'Autre sujet'], errors: { name: 'Veuillez saisir un nom de deux caractères au moins.', email: 'Veuillez saisir une adresse e-mail valide.', message: 'Ajoutez un peu plus de détails (20 caractères minimum).', privacy: 'Veuillez confirmer que nous pouvons utiliser vos informations pour répondre.', configuration: 'Le service de contact est en cours de connexion. Utilisez reach@huygensoft.com pour le moment.', rate_limit: 'Veuillez patienter avant d’envoyer une autre demande.', unavailable: 'Le service de contact est momentanément indisponible. Réessayez ou utilisez reach@huygensoft.com.', generic: 'Nous n’avons pas pu envoyer votre demande. Réessayez ou utilisez reach@huygensoft.com.' } },
    privacy: { eyebrow: 'Confidentialité', title: 'Une explication simple du traitement des demandes.', intro: 'Cet avis couvre les informations envoyées via le formulaire de contact Huygensoft.', collectionTitle: 'Ce que nous recueillons', collectionBody: 'Nous recueillons les informations que vous fournissez : nom, e-mail professionnel, organisation, téléphone, sujet et message.', useTitle: 'Pourquoi nous les utilisons', useBody: 'Nous les utilisons pour comprendre et répondre à votre demande, et conserver une trace appropriée de la conversation.', retentionTitle: 'Durée de conservation', retentionBody: 'Nous conservons les demandes seulement le temps raisonnablement nécessaire pour répondre, gérer la relation et respecter nos obligations.', contactTitle: 'Vos questions', contactBody: 'Pour toute question de confidentialité, écrivez à reach@huygensoft.com.' },
    footer: { line: 'Développement logiciel et conseil IT, rendus plus clairs.', legal: 'Huygensoft Limited · N° d’entreprise 17250183', privacy: 'Confidentialité', companyLink: 'Informations sur l’entreprise' },
    seo: { home: { title: 'Huygensoft | Développement logiciel et conseil IT', description: 'Huygensoft crée des logiciels réfléchis et fournit du conseil IT pour des produits numériques utiles et clairs.' }, services: { title: 'Services | Huygensoft', description: 'Développement logiciel, intégration, automatisation et conseil technique par Huygensoft.' }, company: { title: 'Entreprise | Huygensoft', description: 'Informations sur Huygensoft Limited, société privée britannique.' }, contact: { title: 'Contact | Huygensoft', description: 'Contactez Huygensoft pour le développement logiciel, l’intégration ou le conseil IT.' }, privacy: { title: 'Confidentialité | Huygensoft', description: 'Comment Huygensoft traite les informations envoyées via son formulaire de contact.' } },
  }),
  de: mergeTranslation({
    nav: { home: 'Start', services: 'Leistungen', company: 'Unternehmen', contact: 'Kontakt', language: 'Sprache', theme: 'Farbschema', openMenu: 'Menü öffnen', closeMenu: 'Menü schließen', primaryNavigation: 'Hauptnavigation', skipToContent: 'Zum Inhalt springen', light: 'Helles Design verwenden', dark: 'Dunkles Design verwenden' },
    common: { getInTouch: 'Gespräch beginnen', exploreServices: 'Leistungen entdecken', viewServices: 'Alle Leistungen', learnMore: 'Mehr erfahren', backHome: 'Zur Startseite', privacy: 'Datenschutz', companyNumber: 'Handelsregisternummer', registeredIn: 'Eingetragen in England und Wales', status: 'Status', incorporated: 'Gegründet', registeredOffice: 'Sitz', activities: 'Eingetragene Tätigkeiten', active: 'Aktiv', privateLimited: 'Private Limited Company', source: 'Quelle' },
    home: { eyebrow: 'Softwareentwicklung · IT-Beratung', title: 'Software, die Komplexität einfach macht.', body: 'Huygensoft verwandelt Ideen, getrennte Tools und schwierige Abläufe in durchdachte digitale Produkte.', visualLabel: 'Abstrakte Illustration vernetzter Softwaresysteme.', signal: 'Ein ruhigerer Weg zu bauen', signalValue: 'Klare Systeme. Nützliche Software.', servicesEyebrow: 'Unsere Arbeit', servicesTitle: 'Nützlich gestaltet. Sorgfältig umgesetzt.', servicesBody: 'Von einer gezielten Integration bis zum vollständigen Produkt beginnen wir mit Klarheit und liefern zuverlässige Software.', stepsEyebrow: 'Unser Vorgehen', stepsTitle: 'Weniger Lärm. Mehr Fortschritt.', steps: [{ number: '01', title: 'Zuerst zuhören', copy: 'Wir beginnen mit Menschen, Rahmenbedingungen und dem wichtigen Ergebnis.' }, { number: '02', title: 'Klarheit schaffen', copy: 'Wir machen aus Komplexität einen gemeinsamen Plan.' }, { number: '03', title: 'Sorgfältig bauen', copy: 'Wir liefern bewusste Software mit Raum zur Weiterentwicklung.' }], services: [{ number: '01', title: 'Softwareentwicklung', copy: 'Web-, Desktop- und Produktarbeit, passend zu Ihren tatsächlichen Abläufen.' }, { number: '02', title: 'Integration & Automatisierung', copy: 'Verbinden Sie wichtige Systeme und reduzieren Sie wiederkehrende Arbeit.' }, { number: '03', title: 'Technische Beratung', copy: 'Pragmatische Analyse, Architektur und Lieferung für klare Entscheidungen.' }] },
    services: { eyebrow: 'Leistungen', title: 'Ein ruhiger, kompetenter Partner für komplexe Software.', body: 'Wir verbinden Produktdenken und pragmatische Entwicklung, damit aus Unsicherheit ein funktionierendes System wird.', closingTitle: 'Ein Problem, das einfacher werden soll?', closingBody: 'Sagen Sie uns, was im Weg steht. Wir finden einen sinnvollen nächsten Schritt.', cards: [{ number: '01', title: 'Softwareentwicklung', copy: 'Web-, Desktop- und Produktarbeit, passend zu Ihren tatsächlichen Abläufen.' }, { number: '02', title: 'Integration & Automatisierung', copy: 'Verbinden Sie wichtige Systeme und reduzieren Sie wiederkehrende Arbeit.' }, { number: '03', title: 'Technische Beratung', copy: 'Pragmatische Analyse, Architektur und Lieferung für klare Entscheidungen.' }] },
    company: { eyebrow: 'Das Unternehmen', title: 'Für die Arbeit hinter besserer Software geschaffen.', body: 'Huygensoft Limited ist ein britisches Privatunternehmen für Softwareverlag, Softwareentwicklung und IT-Beratung.', legalTitle: 'Unternehmensinformationen', legalBody: 'Die folgenden Angaben stammen aus dem öffentlichen Companies-House-Register.', activitiesIntro: 'Das Unternehmen ist für folgende Industrieklassifikationen eingetragen:', sourceNote: 'Companies House Übersicht, geprüft am 25. August 2026.' },
    contact: { eyebrow: 'Kontakt', title: 'Beginnen Sie mit dem Problem, nicht mit der Plattform.', body: 'Beschreiben Sie kurz, was Sie verbessern möchten. Das reicht für ein hilfreiches erstes Gespräch.', formTitle: 'Ihre Anfrage', name: 'Name', email: 'Geschäftliche E-Mail', organisation: 'Organisation', phone: 'Telefon (optional)', topic: 'Wobei können wir helfen?', message: 'Erzählen Sie uns vom Vorhaben', privacy: 'Ich stimme zu, dass Huygensoft diese Angaben nutzt, um auf meine Anfrage zu antworten, wie im Datenschutzhinweis beschrieben.', submit: 'Anfrage senden', sending: 'Wird gesendet…', successTitle: 'Danke — Ihre Anfrage ist eingegangen.', successBody: 'Wir haben Ihre Nachricht erhalten und verwenden Ihre Kontaktdaten nur zur Beantwortung.', contactDetails: 'Kontaktdaten', registeredOffice: 'Eingetragener Sitz', selectTopic: 'Thema wählen', topics: ['Neue Software', 'Integration & Automatisierung', 'Technische Beratung', 'Etwas anderes'], errors: { name: 'Bitte geben Sie einen Namen mit mindestens zwei Zeichen ein.', email: 'Bitte geben Sie eine gültige E-Mail-Adresse ein.', message: 'Bitte fügen Sie mehr Details hinzu (mindestens 20 Zeichen).', privacy: 'Bitte bestätigen Sie die Nutzung Ihrer Angaben zur Antwort.', configuration: 'Der Kontaktservice wird gerade verbunden. Schreiben Sie bitte an reach@huygensoft.com.', rate_limit: 'Bitte warten Sie einen Moment, bevor Sie eine weitere Anfrage senden.', unavailable: 'Der Kontaktservice ist vorübergehend nicht verfügbar. Bitte versuchen Sie es erneut oder schreiben Sie an reach@huygensoft.com.', generic: 'Ihre Anfrage konnte nicht gesendet werden. Bitte versuchen Sie es erneut.' } },
    privacy: { eyebrow: 'Datenschutz', title: 'Eine einfache Erklärung zum Umgang mit Anfragen.', intro: 'Dieser Hinweis gilt für Informationen aus dem Huygensoft-Kontaktformular.', collectionTitle: 'Was wir erfassen', collectionBody: 'Wir erfassen die Angaben, die Sie machen: Name, geschäftliche E-Mail, Organisation, Telefon, Thema und Nachricht.', useTitle: 'Warum wir sie verwenden', useBody: 'Wir verwenden sie, um Ihre Anfrage zu verstehen und zu beantworten sowie einen angemessenen Gesprächsnachweis zu führen.', retentionTitle: 'Wie lange wir sie speichern', retentionBody: 'Wir bewahren Anfragedaten nur so lange auf, wie es für die Antwort, die Beziehung und anwendbare Pflichten angemessen nötig ist.', contactTitle: 'Ihre Fragen', contactBody: 'Für Datenschutzfragen schreiben Sie an reach@huygensoft.com.' },
    footer: { line: 'Softwareentwicklung und IT-Beratung, klarer gemacht.', legal: 'Huygensoft Limited · Nr. 17250183', privacy: 'Datenschutz', companyLink: 'Unternehmensinformationen' },
    seo: { home: { title: 'Huygensoft | Softwareentwicklung & IT-Beratung', description: 'Huygensoft entwickelt durchdachte Software und bietet IT-Beratung für klare, nützliche digitale Produkte.' }, services: { title: 'Leistungen | Huygensoft', description: 'Softwareentwicklung, Integration, Automatisierung und technische Beratung von Huygensoft.' }, company: { title: 'Unternehmen | Huygensoft', description: 'Informationen zu Huygensoft Limited, einem britischen Privatunternehmen.' }, contact: { title: 'Kontakt | Huygensoft', description: 'Kontaktieren Sie Huygensoft für Softwareentwicklung, Integration oder IT-Beratung.' }, privacy: { title: 'Datenschutz | Huygensoft', description: 'Wie Huygensoft Informationen aus dem Kontaktformular verarbeitet.' } },
  }),
  es: mergeTranslation({
    nav: { home: 'Inicio', services: 'Servicios', company: 'Empresa', contact: 'Contacto', language: 'Idioma', theme: 'Tema de color', openMenu: 'Abrir menú', closeMenu: 'Cerrar menú', primaryNavigation: 'Navegación principal', skipToContent: 'Saltar al contenido', light: 'Usar tema claro', dark: 'Usar tema oscuro' },
    common: { getInTouch: 'Iniciar una conversación', exploreServices: 'Explorar servicios', viewServices: 'Ver servicios', learnMore: 'Saber más', backHome: 'Volver al inicio', privacy: 'Privacidad', companyNumber: 'Número de empresa', registeredIn: 'Registrada en Inglaterra y Gales', status: 'Estado', incorporated: 'Constituida', registeredOffice: 'Domicilio social', activities: 'Actividades registradas', active: 'Activa', privateLimited: 'Sociedad privada limitada', source: 'Fuente' },
    home: { eyebrow: 'Desarrollo de software · Consultoría TI', title: 'Software que hace simple lo complejo.', body: 'Huygensoft ayuda a las organizaciones a transformar ideas, herramientas desconectadas y procesos difíciles en productos digitales bien pensados.', visualLabel: 'Ilustración abstracta de sistemas de software conectados.', signal: 'Una forma más tranquila de crear', signalValue: 'Sistemas claros. Software útil.', servicesEyebrow: 'Qué hacemos', servicesTitle: 'Útil por diseño. Cuidadoso por defecto.', servicesBody: 'Desde una integración concreta hasta un producto completo, empezamos con claridad y terminamos con software fiable.', stepsEyebrow: 'Cómo trabajamos', stepsTitle: 'Menos ruido. Más avance.', steps: [{ number: '01', title: 'Escuchamos primero', copy: 'Empezamos por las personas, límites y resultado importante.' }, { number: '02', title: 'Aclaramos', copy: 'Convertimos la complejidad en un plan compartido.' }, { number: '03', title: 'Construimos con cuidado', copy: 'Entregamos software intencional, preparado para evolucionar.' }], services: [{ number: '01', title: 'Desarrollo de software', copy: 'Trabajo web, de escritorio y de producto adaptado a sus operaciones reales.' }, { number: '02', title: 'Integración y automatización', copy: 'Conecte los sistemas importantes y elimine tareas repetitivas.' }, { number: '03', title: 'Consultoría técnica', copy: 'Descubrimiento, arquitectura y entrega prácticos para decisiones claras.' }] },
    services: { eyebrow: 'Servicios', title: 'Un socio sereno y capaz para software complejo.', body: 'Combinamos visión de producto e ingeniería práctica para pasar de la incertidumbre a un sistema que funciona.', closingTitle: '¿Un problema que merece simplificarse?', closingBody: 'Cuéntenos qué se interpone. Le ayudaremos a encontrar un siguiente paso útil.', cards: [{ number: '01', title: 'Desarrollo de software', copy: 'Trabajo web, de escritorio y de producto adaptado a sus operaciones reales.' }, { number: '02', title: 'Integración y automatización', copy: 'Conecte los sistemas importantes y elimine tareas repetitivas.' }, { number: '03', title: 'Consultoría técnica', copy: 'Descubrimiento, arquitectura y entrega prácticos para decisiones claras.' }] },
    company: { eyebrow: 'La empresa', title: 'Creada para el trabajo que mejora el software.', body: 'Huygensoft Limited es una sociedad privada británica registrada para publicación de software, desarrollo de software y consultoría TI.', legalTitle: 'Información de la empresa', legalBody: 'Los datos siguientes proceden del registro público de Companies House.', activitiesIntro: 'La empresa está registrada bajo las siguientes actividades de clasificación industrial:', sourceNote: 'Resumen de Companies House, comprobado el 25 de agosto de 2026.' },
    contact: { eyebrow: 'Contacto', title: 'Empiece por el problema, no por la plataforma.', body: 'Cuéntenos qué quiere mejorar. Un resumen breve basta para iniciar una conversación útil.', formTitle: 'Su consulta', name: 'Nombre', email: 'Correo profesional', organisation: 'Organización', phone: 'Teléfono (opcional)', topic: '¿En qué podemos ayudar?', message: 'Cuéntenos sobre el trabajo', privacy: 'Acepto que Huygensoft use estos datos para responder a mi consulta, como se describe en el aviso de privacidad.', submit: 'Enviar consulta', sending: 'Enviando…', successTitle: 'Gracias — hemos recibido su consulta.', successBody: 'Hemos recibido su mensaje y usaremos sus datos de contacto solo para responder a esta consulta.', contactDetails: 'Datos de contacto', registeredOffice: 'Domicilio social', selectTopic: 'Elija un tema', topics: ['Nuevo software', 'Integración y automatización', 'Consultoría técnica', 'Otra cosa'], errors: { name: 'Introduzca un nombre de al menos dos caracteres.', email: 'Introduzca una dirección de correo válida.', message: 'Añada un poco más de detalle (al menos 20 caracteres).', privacy: 'Confirme que podemos usar sus datos para responder.', configuration: 'El servicio de contacto se está conectando. Use reach@huygensoft.com por ahora.', rate_limit: 'Espere un momento antes de enviar otra consulta.', unavailable: 'El servicio de contacto no está disponible temporalmente. Inténtelo de nuevo o use reach@huygensoft.com.', generic: 'No pudimos enviar su consulta. Inténtelo de nuevo.' } },
    privacy: { eyebrow: 'Privacidad', title: 'Una explicación sencilla sobre las consultas.', intro: 'Este aviso cubre la información enviada mediante el formulario de contacto de Huygensoft.', collectionTitle: 'Qué recopilamos', collectionBody: 'Recopilamos los datos que proporciona: nombre, correo profesional, organización, teléfono, tema y mensaje.', useTitle: 'Por qué los usamos', useBody: 'Los usamos para comprender y responder a su consulta y mantener un registro adecuado de la conversación.', retentionTitle: 'Cuánto tiempo los conservamos', retentionBody: 'Conservamos la información de consultas solo el tiempo razonablemente necesario para responder, gestionar la relación y cumplir las obligaciones aplicables.', contactTitle: 'Sus preguntas', contactBody: 'Para preguntas de privacidad, escriba a reach@huygensoft.com.' },
    footer: { line: 'Desarrollo de software y consultoría TI, más claros.', legal: 'Huygensoft Limited · N.º de empresa 17250183', privacy: 'Privacidad', companyLink: 'Información de la empresa' },
    seo: { home: { title: 'Huygensoft | Desarrollo de software y consultoría TI', description: 'Huygensoft crea software considerado y ofrece consultoría TI para productos digitales claros y útiles.' }, services: { title: 'Servicios | Huygensoft', description: 'Desarrollo de software, integración, automatización y consultoría técnica de Huygensoft.' }, company: { title: 'Empresa | Huygensoft', description: 'Información de Huygensoft Limited, una sociedad privada británica.' }, contact: { title: 'Contacto | Huygensoft', description: 'Contacte con Huygensoft para desarrollo de software, integración o consultoría TI.' }, privacy: { title: 'Privacidad | Huygensoft', description: 'Cómo Huygensoft trata la información enviada por su formulario de contacto.' } },
  }),
  pt: mergeTranslation({
    nav: { home: 'Início', services: 'Serviços', company: 'Empresa', contact: 'Contacto', language: 'Idioma', theme: 'Tema de cor', openMenu: 'Abrir menu', closeMenu: 'Fechar menu', primaryNavigation: 'Navegação principal', skipToContent: 'Saltar para o conteúdo', light: 'Usar tema claro', dark: 'Usar tema escuro' },
    common: { getInTouch: 'Iniciar uma conversa', exploreServices: 'Explorar serviços', viewServices: 'Ver serviços', learnMore: 'Saber mais', backHome: 'Voltar ao início', privacy: 'Privacidade', companyNumber: 'Número da empresa', registeredIn: 'Registada em Inglaterra e País de Gales', status: 'Estado', incorporated: 'Constituída', registeredOffice: 'Sede registada', activities: 'Atividades registadas', active: 'Ativa', privateLimited: 'Sociedade privada limitada', source: 'Fonte' },
    home: { eyebrow: 'Desenvolvimento de software · Consultoria de TI', title: 'Software que torna simples o que é complexo.', body: 'A Huygensoft ajuda organizações a transformar ideias, ferramentas desligadas e processos difíceis em produtos digitais ponderados.', visualLabel: 'Ilustração abstrata de sistemas de software ligados.', signal: 'Uma forma mais tranquila de construir', signalValue: 'Sistemas claros. Software útil.', servicesEyebrow: 'O que fazemos', servicesTitle: 'Útil por design. Cuidado por definição.', servicesBody: 'De uma integração focada a um produto completo, começamos com clareza e terminamos com software em que as pessoas podem confiar.', stepsEyebrow: 'Como trabalhamos', stepsTitle: 'Menos ruído. Mais progresso.', steps: [{ number: '01', title: 'Ouvimos primeiro', copy: 'Começamos pelas pessoas, limites e resultado que importam.' }, { number: '02', title: 'Tornamos claro', copy: 'Transformamos complexidade num plano partilhado.' }, { number: '03', title: 'Construímos com cuidado', copy: 'Entregamos software deliberado, pronto para evoluir.' }], services: [{ number: '01', title: 'Desenvolvimento de software', copy: 'Trabalho web, desktop e de produto pensado para as suas operações reais.' }, { number: '02', title: 'Integração e automação', copy: 'Ligue sistemas importantes e reduza trabalho repetitivo.' }, { number: '03', title: 'Consultoria técnica', copy: 'Descoberta, arquitetura e entrega práticas para decisões claras.' }] },
    services: { eyebrow: 'Serviços', title: 'Um parceiro sereno e competente para software complexo.', body: 'Juntamos pensamento de produto e engenharia prática para levar equipas da incerteza a um sistema funcional.', closingTitle: 'Um problema que vale a pena simplificar?', closingBody: 'Diga-nos o que está a impedir o progresso. Encontraremos um próximo passo útil.', cards: [{ number: '01', title: 'Desenvolvimento de software', copy: 'Trabalho web, desktop e de produto pensado para as suas operações reais.' }, { number: '02', title: 'Integração e automação', copy: 'Ligue sistemas importantes e reduza trabalho repetitivo.' }, { number: '03', title: 'Consultoria técnica', copy: 'Descoberta, arquitetura e entrega práticas para decisões claras.' }] },
    company: { eyebrow: 'A empresa', title: 'Criada para o trabalho por trás de software melhor.', body: 'Huygensoft Limited é uma sociedade privada do Reino Unido registada para publicação de software, desenvolvimento de software e consultoria de TI.', legalTitle: 'Informação da empresa', legalBody: 'Os dados abaixo vêm do registo público da Companies House.', activitiesIntro: 'A empresa está registada nas seguintes atividades de classificação industrial:', sourceNote: 'Resumo da Companies House, verificado em 25 de agosto de 2026.' },
    contact: { eyebrow: 'Contacto', title: 'Comece pelo problema, não pela plataforma.', body: 'Conte-nos o que pretende melhorar. Um resumo curto é suficiente para começar uma conversa útil.', formTitle: 'O seu pedido', name: 'Nome', email: 'E-mail profissional', organisation: 'Organização', phone: 'Telefone (opcional)', topic: 'Como podemos ajudar?', message: 'Conte-nos sobre o trabalho', privacy: 'Concordo que a Huygensoft use estes dados para responder ao meu pedido, conforme descrito no aviso de privacidade.', submit: 'Enviar pedido', sending: 'A enviar…', successTitle: 'Obrigado — recebemos o seu pedido.', successBody: 'Recebemos a sua mensagem e usaremos os seus contactos apenas para responder a este pedido.', contactDetails: 'Dados de contacto', registeredOffice: 'Sede registada', selectTopic: 'Escolha um tópico', topics: ['Novo software', 'Integração e automação', 'Consultoria técnica', 'Outra coisa'], errors: { name: 'Introduza um nome com pelo menos dois caracteres.', email: 'Introduza um endereço de e-mail válido.', message: 'Adicione mais detalhes (pelo menos 20 caracteres).', privacy: 'Confirme que podemos usar os seus dados para responder.', configuration: 'O serviço de contacto está a ser ligado. Use reach@huygensoft.com por agora.', rate_limit: 'Aguarde um momento antes de enviar outro pedido.', unavailable: 'O serviço de contacto está temporariamente indisponível. Tente novamente ou use reach@huygensoft.com.', generic: 'Não foi possível enviar o seu pedido. Tente novamente.' } },
    privacy: { eyebrow: 'Privacidade', title: 'Uma explicação simples sobre o tratamento de pedidos.', intro: 'Este aviso cobre a informação enviada através do formulário de contacto da Huygensoft.', collectionTitle: 'O que recolhemos', collectionBody: 'Recolhemos os dados que escolher fornecer: nome, e-mail profissional, organização, telefone, tópico e mensagem.', useTitle: 'Porque os usamos', useBody: 'Usamos os seus dados para compreender e responder ao pedido e manter um registo adequado da conversa.', retentionTitle: 'Durante quanto tempo os guardamos', retentionBody: 'Guardamos informação de pedidos apenas pelo tempo razoavelmente necessário para responder, gerir a relação e cumprir obrigações aplicáveis.', contactTitle: 'As suas questões', contactBody: 'Para questões de privacidade, escreva para reach@huygensoft.com.' },
    footer: { line: 'Desenvolvimento de software e consultoria de TI, mais claros.', legal: 'Huygensoft Limited · N.º da empresa 17250183', privacy: 'Privacidade', companyLink: 'Informação da empresa' },
    seo: { home: { title: 'Huygensoft | Desenvolvimento de software e consultoria de TI', description: 'A Huygensoft cria software ponderado e presta consultoria de TI para produtos digitais claros e úteis.' }, services: { title: 'Serviços | Huygensoft', description: 'Desenvolvimento de software, integração, automação e consultoria técnica pela Huygensoft.' }, company: { title: 'Empresa | Huygensoft', description: 'Informação sobre a Huygensoft Limited, sociedade privada do Reino Unido.' }, contact: { title: 'Contacto | Huygensoft', description: 'Contacte a Huygensoft para desenvolvimento de software, integração ou consultoria de TI.' }, privacy: { title: 'Privacidade | Huygensoft', description: 'Como a Huygensoft trata informação enviada pelo formulário de contacto.' } },
  }),
  ar: mergeTranslation({
    nav: { home: 'الرئيسية', services: 'الخدمات', company: 'الشركة', contact: 'تواصل', language: 'اللغة', theme: 'نمط الألوان', openMenu: 'فتح القائمة', closeMenu: 'إغلاق القائمة', primaryNavigation: 'التنقل الرئيسي', skipToContent: 'انتقل إلى المحتوى', light: 'استخدام النمط الفاتح', dark: 'استخدام النمط الداكن' },
    common: { getInTouch: 'ابدأ محادثة', exploreServices: 'استكشف الخدمات', viewServices: 'عرض الخدمات', learnMore: 'اعرف المزيد', backHome: 'العودة للرئيسية', privacy: 'الخصوصية', companyNumber: 'رقم الشركة', registeredIn: 'مسجلة في إنجلترا وويلز', status: 'الحالة', incorporated: 'تأسست', registeredOffice: 'المكتب المسجل', activities: 'الأنشطة المسجلة', active: 'نشطة', privateLimited: 'شركة خاصة محدودة', source: 'المصدر' },
    home: { eyebrow: 'تطوير البرمجيات · استشارات تقنية المعلومات', title: 'برمجيات تجعل المعقّد بسيطاً.', body: 'تساعد Huygensoft المؤسسات على تحويل الأفكار والأدوات المنفصلة والإجراءات الصعبة إلى منتجات رقمية مدروسة.', visualLabel: 'رسم تجريدي لأنظمة برمجية مترابطة.', signal: 'طريقة أهدأ للبناء', signalValue: 'أنظمة واضحة. برمجيات مفيدة.', servicesEyebrow: 'ما نفعله', servicesTitle: 'مفيد بالتصميم. مدروس بطبيعته.', servicesBody: 'من تكامل محدد إلى منتج كامل، نبدأ بالوضوح وننتهي ببرمجيات يمكن الاعتماد عليها.', stepsEyebrow: 'كيف نعمل', stepsTitle: 'ضوضاء أقل. تقدم أكبر.', steps: [{ number: '01', title: 'نستمع أولاً', copy: 'نبدأ بالأشخاص والقيود والنتيجة المهمة.' }, { number: '02', title: 'نجعل الأمر واضحاً', copy: 'نحوّل التعقيد إلى خطة مشتركة.' }, { number: '03', title: 'نبني بعناية', copy: 'نقدم برمجيات متعمدة وقابلة للتطور.' }], services: [{ number: '01', title: 'تطوير البرمجيات', copy: 'حلول ويب وسطح مكتب ومنتجات تناسب طريقة عمل مؤسستك.' }, { number: '02', title: 'التكامل والأتمتة', copy: 'اربط الأنظمة المهمة وأزل العمل المتكرر.' }, { number: '03', title: 'الاستشارات التقنية', copy: 'استكشاف وهندسة وتسليم عملي لقرارات أوضح.' }] },
    services: { eyebrow: 'الخدمات', title: 'شريك هادئ وقادر للبرمجيات المعقدة.', body: 'نجمع تفكير المنتجات والهندسة العملية لنقل الفرق من عدم اليقين إلى نظام يعمل.', closingTitle: 'هل لديك مشكلة تستحق التبسيط؟', closingBody: 'أخبرنا بما يقف في طريقك. سنساعدك على إيجاد خطوة تالية مفيدة.', cards: [{ number: '01', title: 'تطوير البرمجيات', copy: 'حلول ويب وسطح مكتب ومنتجات تناسب طريقة عمل مؤسستك.' }, { number: '02', title: 'التكامل والأتمتة', copy: 'اربط الأنظمة المهمة وأزل العمل المتكرر.' }, { number: '03', title: 'الاستشارات التقنية', copy: 'استكشاف وهندسة وتسليم عملي لقرارات أوضح.' }] },
    company: { eyebrow: 'الشركة', title: 'مبنية للعمل وراء برمجيات أفضل.', body: 'Huygensoft Limited شركة بريطانية خاصة مسجلة لنشر البرمجيات وتطويرها واستشارات تقنية المعلومات.', legalTitle: 'معلومات الشركة', legalBody: 'الحقائق أدناه مأخوذة من سجل Companies House العام.', activitiesIntro: 'الشركة مسجلة تحت أنشطة التصنيف الصناعي التالية:', sourceNote: 'نظرة عامة على Companies House، تم التحقق منها في 25 أغسطس 2026.' },
    contact: { eyebrow: 'تواصل', title: 'ابدأ بالمشكلة، لا بالمنصة.', body: 'أخبرنا قليلاً عما تريد تحسينه. ملخص موجز يكفي لبدء محادثة مفيدة.', formTitle: 'استفسارك', name: 'الاسم', email: 'البريد الإلكتروني للعمل', organisation: 'المؤسسة', phone: 'الهاتف (اختياري)', topic: 'كيف يمكننا المساعدة؟', message: 'أخبرنا عن العمل', privacy: 'أوافق على أن تستخدم Huygensoft هذه التفاصيل للرد على استفساري، كما هو موضح في إشعار الخصوصية.', submit: 'إرسال الاستفسار', sending: 'جارٍ الإرسال…', successTitle: 'شكراً — تم استلام استفسارك.', successBody: 'استلمنا رسالتك وسنستخدم بيانات الاتصال للرد على هذا الاستفسار فقط.', contactDetails: 'تفاصيل التواصل', registeredOffice: 'المكتب المسجل', selectTopic: 'اختر موضوعاً', topics: ['برمجيات جديدة', 'تكامل وأتمتة', 'استشارات تقنية', 'شيء آخر'], errors: { name: 'يرجى إدخال اسم من حرفين على الأقل.', email: 'يرجى إدخال بريد إلكتروني صالح.', message: 'يرجى إضافة مزيد من التفاصيل (20 حرفاً على الأقل).', privacy: 'يرجى تأكيد إمكانية استخدام بياناتك للرد.', configuration: 'يتم توصيل خدمة التواصل. استخدم reach@huygensoft.com حالياً.', rate_limit: 'يرجى الانتظار قليلاً قبل إرسال استفسار آخر.', unavailable: 'خدمة التواصل غير متاحة مؤقتاً. حاول لاحقاً أو استخدم reach@huygensoft.com.', generic: 'تعذر إرسال استفسارك. حاول مرة أخرى.' } },
    privacy: { eyebrow: 'الخصوصية', title: 'شرح بسيط لكيفية التعامل مع الاستفسارات.', intro: 'يغطي هذا الإشعار المعلومات المرسلة عبر نموذج تواصل Huygensoft.', collectionTitle: 'ما نجمعه', collectionBody: 'نجمع التفاصيل التي تختار تقديمها: الاسم وبريد العمل والمؤسسة والهاتف والموضوع والرسالة.', useTitle: 'لماذا نستخدمها', useBody: 'نستخدم التفاصيل لفهم استفسارك والرد عليه وحفظ سجل مناسب للمحادثة.', retentionTitle: 'مدة الاحتفاظ بها', retentionBody: 'نحتفظ بمعلومات الاستفسارات فقط للمدة اللازمة بشكل معقول للرد وإدارة العلاقة والوفاء بالالتزامات المطبقة.', contactTitle: 'أسئلتك', contactBody: 'لأسئلة الخصوصية، تواصل مع reach@huygensoft.com.' },
    footer: { line: 'تطوير البرمجيات واستشارات تقنية المعلومات، بوضوح أكبر.', legal: 'Huygensoft Limited · رقم الشركة 17250183', privacy: 'الخصوصية', companyLink: 'معلومات الشركة' },
    seo: { home: { title: 'Huygensoft | تطوير البرمجيات واستشارات تقنية المعلومات', description: 'تقدم Huygensoft برمجيات مدروسة واستشارات تقنية لمنتجات رقمية واضحة ومفيدة.' }, services: { title: 'الخدمات | Huygensoft', description: 'تطوير البرمجيات والتكامل والأتمتة والاستشارات التقنية من Huygensoft.' }, company: { title: 'الشركة | Huygensoft', description: 'معلومات عن Huygensoft Limited، شركة بريطانية خاصة.' }, contact: { title: 'تواصل | Huygensoft', description: 'تواصل مع Huygensoft لتطوير البرمجيات أو التكامل أو استشارات تقنية المعلومات.' }, privacy: { title: 'الخصوصية | Huygensoft', description: 'كيف تتعامل Huygensoft مع المعلومات المرسلة من نموذج التواصل.' } },
  }),
  zh: mergeTranslation({
    nav: { home: '首页', services: '服务', company: '公司', contact: '联系', language: '语言', theme: '配色主题', openMenu: '打开菜单', closeMenu: '关闭菜单', primaryNavigation: '主导航', skipToContent: '跳至内容', light: '使用浅色主题', dark: '使用深色主题' },
    common: { getInTouch: '开始交流', exploreServices: '探索服务', viewServices: '查看全部服务', learnMore: '了解更多', backHome: '返回首页', privacy: '隐私', companyNumber: '公司编号', registeredIn: '在英格兰和威尔士注册', status: '状态', incorporated: '成立日期', registeredOffice: '注册地址', activities: '注册业务活动', active: '正常运营', privateLimited: '私人有限公司', source: '来源' },
    home: { eyebrow: '软件开发 · IT 咨询', title: '让复杂变得简单的软件。', body: 'Huygensoft 帮助组织将想法、割裂的工具和困难的流程转变为经过深思熟虑的数字产品。', visualLabel: '互联软件系统的抽象插图。', signal: '更从容的构建方式', signalValue: '清晰的系统。实用的软件。', servicesEyebrow: '我们提供什么', servicesTitle: '以实用为设计原则。以周全为默认选择。', servicesBody: '无论是一次聚焦的集成还是完整的产品，我们从清晰开始，以可靠的软件结束。', stepsEyebrow: '我们的工作方式', stepsTitle: '更少噪音。更多推进。', steps: [{ number: '01', title: '先倾听', copy: '我们从人员、限制条件和真正重要的结果开始。' }, { number: '02', title: '建立清晰认识', copy: '我们把复杂性转化为团队可共用的计划。' }, { number: '03', title: '用心构建', copy: '我们交付有意识设计、能够演进的软件。' }], services: [{ number: '01', title: '软件开发', copy: '围绕实际业务运营构建 Web、桌面和产品软件。' }, { number: '02', title: '集成与自动化', copy: '连接重要系统，减少重复工作，让信息顺畅流动。' }, { number: '03', title: '技术咨询', copy: '通过务实的调研、架构和交付支持清晰决策。' }] },
    services: { eyebrow: '服务', title: '复杂软件的从容可靠合作伙伴。', body: '我们结合产品思维与务实工程，帮助团队从不确定性走向真正可用的系统。', closingTitle: '有值得简化的问题吗？', closingBody: '请告诉我们是什么阻碍了您。我们会帮助您找到有用的下一步。', cards: [{ number: '01', title: '软件开发', copy: '围绕实际业务运营构建 Web、桌面和产品软件。' }, { number: '02', title: '集成与自动化', copy: '连接重要系统，减少重复工作，让信息顺畅流动。' }, { number: '03', title: '技术咨询', copy: '通过务实的调研、架构和交付支持清晰决策。' }] },
    company: { eyebrow: '公司', title: '为更好软件背后的工作而生。', body: 'Huygensoft Limited 是一家英国私人有限公司，注册业务包括软件出版、软件开发及 IT 咨询。', legalTitle: '公司信息', legalBody: '以下资料来自 Companies House 公开登记册。', activitiesIntro: '公司注册的标准行业分类活动如下：', sourceNote: 'Companies House 公司概览，核实于 2026 年 8 月 25 日。' },
    contact: { eyebrow: '联系', title: '从问题开始，而不是从平台开始。', body: '告诉我们您想改善什么。简短的描述就足以开始一次有价值的交流。', formTitle: '您的咨询', name: '姓名', email: '工作邮箱', organisation: '机构', phone: '电话（可选）', topic: '我们可以如何帮助您？', message: '告诉我们相关工作', privacy: '我同意 Huygensoft 按隐私声明所述使用这些资料来回复我的咨询。', submit: '发送咨询', sending: '发送中…', successTitle: '谢谢 — 我们已收到您的咨询。', successBody: '我们已安全收到您的信息，只会使用您的联系方式来回复本次咨询。', contactDetails: '联系资料', registeredOffice: '注册地址', selectTopic: '选择主题', topics: ['新软件', '集成与自动化', '技术咨询', '其他'], errors: { name: '请输入至少两个字符的姓名。', email: '请输入有效的电子邮件地址。', message: '请补充更多信息（至少 20 个字符）。', privacy: '请确认我们可以使用您的资料来回复。', configuration: '联系服务正在连接。请暂时使用 reach@huygensoft.com。', rate_limit: '请稍候再发送另一项咨询。', unavailable: '联系服务暂时不可用。请稍后重试或使用 reach@huygensoft.com。', generic: '无法发送您的咨询。请重试。' } },
    privacy: { eyebrow: '隐私', title: '关于如何处理咨询的简单说明。', intro: '本声明适用于通过 Huygensoft 联系表单发送的信息。', collectionTitle: '我们收集什么', collectionBody: '我们收集您选择提供的资料：姓名、工作邮箱、机构、电话、主题和留言。', useTitle: '我们为何使用它', useBody: '我们使用这些资料来了解和回复您的咨询，并保留适当的交流记录。', retentionTitle: '我们保留多久', retentionBody: '我们仅在回复、管理关系和履行适用义务所合理需要的时间内保留咨询资料。', contactTitle: '您的问题', contactBody: '如有隐私问题，请联系 reach@huygensoft.com。' },
    footer: { line: '软件开发与 IT 咨询，变得更清晰。', legal: 'Huygensoft Limited · 公司编号 17250183', privacy: '隐私', companyLink: '公司信息' },
    seo: { home: { title: 'Huygensoft | 软件开发与 IT 咨询', description: 'Huygensoft 提供经过深思熟虑的软件和 IT 咨询，专注于清晰实用的数字产品。' }, services: { title: '服务 | Huygensoft', description: 'Huygensoft 提供软件开发、集成、自动化与技术咨询。' }, company: { title: '公司 | Huygensoft', description: 'Huygensoft Limited 的公司信息，一家英国私人有限公司。' }, contact: { title: '联系 | Huygensoft', description: '联系 Huygensoft 讨论软件开发、集成或 IT 咨询。' }, privacy: { title: '隐私 | Huygensoft', description: 'Huygensoft 如何处理通过联系表单提交的信息。' } },
  }),
};

export function isLocale(value: string | null | undefined): value is Locale {
  return localeOptions.some((option) => option.code === value);
}

export function getLocaleOption(locale: Locale) {
  return localeOptions.find((option) => option.code === locale) ?? localeOptions[0];
}

export function detectBrowserLocale(): Locale {
  const browserLocales = typeof navigator === 'undefined' ? [] : navigator.languages;
  for (const browserLocale of browserLocales) {
    const candidate = browserLocale.toLowerCase().split('-')[0];
    if (isLocale(candidate)) return candidate;
  }
  return 'en';
}
